export const CommonActionId = {
  EXPAND_ALL: "ExpandAll",
  COLLAPSE_ALL: "CollapseAll",
  EXPAND_SELECTION: "EditorSelectWord",
  SHRINK_SELECTION: "EditorUnSelectWord",
  GO_TO_ACTION: "GotoAction",
  GO_TO_FILE: "GotoFile",
  SHOW_INTENTION_ACTIONS: "ShowIntentionActions",
  EDIT_SOURCE: "Documentation.EditSource",
  SHOW_SEARCH_HISTORY: "ShowSearchHistory",
  COPY_REFERENCE: "CopyReference",
  REFRESH: "Refresh",
  COPY: "$Copy",
  CUT: "$Cut",
  PASTE: "$Paste",
  DELETE: "$Delete",
  CODE_COMPLETION: "CodeCompletion",
};
