export const editorActionIds = {
  EXPAND_REGION: "ExpandRegion",
  EXPAND_REGION_RECURSIVELY: "ExpandRegionRecursively",
  EXPAND_ALL_REGIONS: "ExpandAllRegions",
  EXPAND_ALL_TO_LEVEL: "ExpandToLevel",
  EXPAND_ALL_TO_LEVEL1: "ExpandToLevel1",
  EXPAND_ALL_TO_LEVEL2: "ExpandToLevel2",
  EXPAND_ALL_TO_LEVEL3: "ExpandToLevel3",
  EXPAND_ALL_TO_LEVEL4: "ExpandToLevel4",
  EXPAND_ALL_TO_LEVEL5: "ExpandToLevel5",
  COLLAPSE_REGION: "CollapseRegion",
  COLLAPSE_REGION_RECURSIVELY: "CollapseRegionRecursively",
  COLLAPSE_ALL_REGIONS: "CollapseAllRegions",
  COLLAPSE_DOC_COMMENTS: "CollapseDocComments",
  TOGGLE_FOLDING: "ToggleFolding",
  EDITOR_LANG_POPUP_MENU: "EditorLangPopupMenu",
  CompareClipboardWithSelection: "CompareClipboardWithSelection",
};
